server:
  port: ${PORT}

spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: ${JDBC_DATABASE_DRIVER:}
    url: jdbc:mysql://${JDBC_DATABASE_HOST:localhost}:${JDBC_DATABASE_PORT:}/${JDBC_DATABASE_NAME:}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}

payment:
  type: vnpay
  vnpay:
    url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    return-url: ${VNPAY_RETURN_URL:https://front-end.huongcungbookstore.com/payment/success}
    tmn-code: ${VNPAY_TMN_CODE}
    hash-secret: ${VNPAY_HASH_SECRET}
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    timezone: ${TIMEZONE}

eureka:
  #  instance:
  #    prefer-ip-address: true
  #    ip-address: 192.168.56.1
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
